[project]
name = "vibot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
    "jupyterlab>=4.4.2",
    "nautilus-trader>=1.217.0",
    "pydantic-ai>=0.2.6",
]
